CREATE TEMP TABLE xloans AS SELECT agre.id,agreement_number,agre.date_start,agre.date_end,brn.code AS branch_code,customer_id,prod.name,customer_type_id,loans.amount,loans.repayment_interest_date,loans.repayment_maindebt_date,loans.accrual_basis_id,loans.accrual_method_id,cur.code,loans.maindebt_repayment_freq_id,loans.interest_repayment_freq_id FROM common.agreement AS agre JOIN customers.customer AS cust ON agre.customer_id = cust.id JOIN common.branch AS brn ON agre.branch_id = brn.id JOIN loans.loan_agreement AS loans ON agre.id = loans.agreement_id JOIN common.product AS prod ON agre.product_id = prod.id JOIN common.currency AS cur ON loans.currency_id = cur.id WHERE agre.status = 'ACTIVE';
SELECT * FROM xloans;

CREATE TEMP TABLE xcustdop AS SELECT cust.id,cust.customer_type_id,extfld.code,extfld.name,extval.row_id,extval.value FROM customers.customer AS cust JOIN (SELECT DISTINCT customer_id FROM xloans) AS ccc ON cust.id = ccc.customer_id JOIN customers.customer_extended_field_values AS extval ON extval.customer_id = cust.id JOIN customers.customer_extended_fields AS extfld ON extval.cust_ext_field_id = extfld.id;

CREATE TEMP TABLE xloandop AS SELECT agre.id,extfld.code,extfld.name,extval.row_id,extval.value FROM common.agreement AS agre JOIN (SELECT DISTINCT id FROM xloans) AS lll ON agre.id = lll.id JOIN common.agreement_extended_field_values AS extval ON agre.id = extval.agreement_id JOIN common.agreement_extended_fields AS extfld ON extval.agreement_ext_field_id = extfld.id;

CREATE TEMP TABLE xloanrate AS SELECT agre.id,typ.code,typ.description,rate.start_date,rate.is_percent,cur.code,rate.value FROM common.agreement AS agre JOIN (SELECT DISTINCT id FROM xloans) AS lll ON agre.id = lll.id JOIN loans.loan_agreement AS la ON la.agreement_id = agre.id JOIN loans.loan_agreement_rp_value AS rate ON la.id = rate.loan_agreement_id JOIN common.currency AS cur ON rate.value_currency_id = cur.id JOIN loans.repayment_type AS typ ON rate.repayment_type_id = typ.id;

CREATE TEMP TABLE xloanost AS SELECT agre.id,typ.code AS stype,typ.description,cur.code AS currency,sub.account_number,ost.balance FROM common.agreement AS agre JOIN (SELECT DISTINCT id FROM xloans) AS lll ON agre.id = lll.id JOIN accounts.subaccount AS sub ON sub.agreement_id = agre.id JOIN accounts.subaccount_type AS typ ON typ.id = sub.subaccount_type_id JOIN common.currency AS cur ON sub.currency_id = cur.id JOIN accounts.subaccount_turnover AS ost ON ost.subaccount_id = sub.id;

CREATE TEMP TABLE xloanrep AS SELECT agre.id,pay.target_date,pay.amount,pay.amount_principal_before,pay.amount_principal_after FROM common.agreement AS agre JOIN (SELECT DISTINCT id FROM xloans) AS lll ON agre.id = lll.id JOIN loans.loan_agreement AS la ON la.agreement_id = agre.id JOIN loans.loan_repayment_schedule AS rep ON la.id = rep.loan_agreement_id AND rep.type = 'TYPE_PAYMENTS' AND rep.status = 'ACTIVE' JOIN loans.loan_repayment_schedule_item AS pay ON pay.loan_repayment_schedule_id = rep.id JOIN loans.repayment_type AS subtyp ON pay.repayment_type_id = subtyp.id;

CREATE TEMP TABLE xloanpen AS SELECT agre.id,acr.repayment_type_id,SUM(acr.remained) FROM common.agreement AS agre JOIN (SELECT DISTINCT id FROM xloans) AS lll ON agre.id = lll.id JOIN loans.loan_agreement AS la ON la.agreement_id = agre.id JOIN loans.loan_agreement_accrual AS acr ON la.id = acr.loan_agreement_id AND acr.repayment_type_id in (18,19) AND acr.state = 'COUNTED' GROUP BY agre.id,acr.repayment_type_id;
